[build]
builder = "nixpacks"
buildCommand = "./mvnw clean package -DskipTests"

[deploy]
startCommand = "java -jar target/backend-0.0.1-SNAPSHOT.jar --spring.profiles.active=prod"
healthcheckPath = "/api/actuator/health"
healthcheckTimeout = 100 